Extension { #name : #WATagBrush }

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesome [

	self class: 'fa'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesome2x [

	self class: 'fa-2x'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesome3x [

	self class: 'fa-3x'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesome4x [

	self class: 'fa-4x'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesome5x [

	self class: 'fa-5x'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeAdjustIcon [

	self class: 'fa-adjust'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeAlignCenterIcon [

	self class: 'fa-align-center'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeAlignJustifyIcon [

	self class: 'fa-align-justify'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeAlignLeftIcon [

	self class: 'fa-align-left'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeAlignRightIcon [

	self class: 'fa-align-right'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowCircleDownIcon [

	self class: 'fa-arrow-circle-down'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowCircleLeftIcon [

	self class: 'fa-arrow-circle-left'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowCircleOutlinedDownIcon [

	self class: 'fa-arrow-circle-o-down'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowCircleOutlinedUpIcon [

	self class: 'fa-arrow-circle-o-up'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowCircleRightIcon [

	self class: 'fa-arrow-circle-right'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowCircleUpIcon [

	self class: 'fa-arrow-circle-up'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowDownIcon [

	self class: 'fa-arrow-down'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowLeftIcon [

	self class: 'fa-arrow-left'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowRigtIcon [

	self class: 'fa-arrow-right'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowUpIcon [

	self class: 'fa-arrow-up'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowsAlternativeIcon [

	self class: 'fa-arrows-alt'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowsHorizontalIcon [

	self class: 'fa-arrows-h'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowsIcon [

	self class: 'fa-arrows'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeArrowsVerticalIcon [

	self class: 'fa-arrows-v'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeAsteriskIcon [

	self class: 'fa-asterisk'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBackwardIcon [

	self class: 'fa-backward'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBanIcon [

	self class: 'fa-ban'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBarChartOutlinedIcon [

	self class: 'fa-bar-chart-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBarcodeIcon [

	self class: 'fa-barcode'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBarsIcon [

	self class: 'fa-bars'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBellIcon [

	self class: 'fa-bell'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBoldIcon [

	self class: 'fa-bold'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBoltIcon [

	self class: 'fa-bolt'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBookIcon [

	self class: 'fa-book'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBookmarkIcon [

	self class: 'fa-bookmark'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBookmarkOutlinedIcon [

	self class: 'fa-bookmark-o'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeBorder [

	self class: 'fa-border'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBriefcaseIcon [

	self class: 'fa-briefcase'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeBullhornIcon [

	self class: 'fa-bullhorn'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCalendarIcon [

	self class: 'fa-calendar'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCameraIcon [

	self class: 'fa-camera'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCameraRetroIcon [

	self class: 'fa-camera-retro'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCaretDownIcon [

	self class: 'fa-caret-down'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCaretLeftIcon [

	self class: 'fa-caret-left'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCaretRightIcon [

	self class: 'fa-caret-right'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCaretUpIcon [

	self class: 'fa-caret-up'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCertificateIcon [

	self class: 'fa-certificate'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeChainIcon [

	self class: 'fa-chain'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCheckCircleIcon [

	self class: 'fa-check-circle'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCheckCircleOutlinedIcon [

	self class: 'fa-check-circle-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCheckIcon [

	self class: 'fa-check'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCheckSquareOutlinedIcon [

	self class: 'fa-check-square-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeChevronDownIcon [

	self class: 'fa-chevron-down'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeChevronLeftIcon [

	self class: 'fa-chevron-left'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeChevronRightIcon [

	self class: 'fa-chevron-right'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeChevronUpIcon [

	self class: 'fa-chevron-up'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeClockOutlinedIcon [

	self class: 'fa-clock-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCloudIcon [

	self class: 'fa-cloud'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCogIcon [

	self class: 'fa-cog'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCogsIcon [

	self class: 'fa-cogs'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeColumnsIcon [

	self class: 'fa-columns'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCommentIcon [

	self class: 'fa-comment'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCommentOutlinedIcon [

	self class: 'fa-comment-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCommentsIcon [

	self class: 'fa-comments'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCommentsOutlinedIcon [

	self class: 'fa-comments-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCompressIcon [

	self class: 'fa-compress'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCopyIcon [

	self class: 'fa-copy'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCreditCardIcon [

	self class: 'fa-credit-card'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCrosshairsIcon [

	self class: 'fa-crosshairs'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeCutIcon [

	self class: 'fa-cut'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeDashbordIcon [

	self class: 'fa-dashboard'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeDedentIcon [

	self class: 'fa-dedent'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeDownloadIcon [

	self class: 'fa-download'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeEditIcon [

	self class: 'fa-edit'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeEjectIcon [

	self class: 'fa-eject'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeEnvelopeIcon [

	self class: 'fa-envelope'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeExclamationCircleIcon [

	self class: 'fa-exclamation-circle'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeExclamationTriangleIcon [

	self class: 'fa-warning'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeExpandIcon [

	self class: 'fa-expand'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeExternalLinkIcon [

	self class: 'fa-external-link'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeEyeIcon [

	self class: 'fa-eye'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeEyeSlashIcon [

	self class: 'fa-eye-slash'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFacebookIcon [

	self class: 'fa-facebook'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFacebookSquareIcon [

	self class: 'fa-facebook-square'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFastBackwardIcon [

	self class: 'fa-fast-backward'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFastForwardIcon [

	self class: 'fa-fast-forward'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFileOutlinedIcon [

	self class: 'fa-file-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFilesOutlinedIcon [

	self class: 'fa-files-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFilmIcon [

	self class: 'fa-film'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFilterIcon [

	self class: 'fa-filter'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFireIcon [

	self class: 'fa-fire'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFlagIcon [

	self class: 'fa-flag'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFlashIcon [

	self class: 'fa-flash'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFlaskIcon [

	self class: 'fa-flask'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeFlipHorizontal [

	self class: 'fa-flip-horizontal'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeFlipVertical [

	self class: 'fa-flip-vertical'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFloppyOutlinedIcon [

	self class: 'fa-floppy-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFolderIcon [

	self class: 'fa-folder'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFolderOpenIcon [

	self class: 'fa-folder-open'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeFontIcon [

	self class: 'fa-font'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeForwardIcon [

	self class: 'fa-forward'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeGavelIcon [

	self class: 'fa-gavel'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeGearIcon [

	self class: 'fa-gear'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeGearsIcon [

	self class: 'fa-gears'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeGiftIcon [

	self class: 'fa-gift'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeGithubIcon [

	self class: 'fa-github'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeGithubSquareIcon [

	self class: 'fa-trophy'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeGlassIcon [

	self class: 'fa-glass'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeGlobeIcon [

	self class: 'fa-globe'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeGooglePlusIcon [

	self class: 'fa-google-plus'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeGooglePlusSquareIcon [

	self class: 'fa-google-plus-square'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeGroupIcon [

	self class: 'fa-group'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeHDDOutlinedIcon [

	self class: 'fa-hdd-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeHandOutlinedDownIcon [

	self class: 'fa-hand-o-down'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeHandOutlinedLeftIcon [

	self class: 'fa-hand-o-left'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeHandOutlinedRightIcon [

	self class: 'fa-hand-o-right'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeHandOutlinedUpIcon [

	self class: 'fa-hand-o-up'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeHeadphonesIcon [

	self class: 'fa-headphones'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeHeartIcon [

	self class: 'fa-heart'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeHeartOutlinedIcon [

	self class: 'fa-heart-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeHomeIcon [

	self class: 'fa-home'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeIdentIcon [

	self class: 'fa-indent'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeInboxIcon [

	self class: 'fa-inbox'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeInfoCircleIcon [

	self class: 'fa-info-circle'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeInverse [

	self class: 'fa-inverse'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeItalicIcon [

	self class: 'fa-italic'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeKeyIcon [

	self class: 'fa-key'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeLarge [

	self class: 'fa-lg'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeLeafIcon [

	self class: 'fa-leaf'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeLegalIcon [

	self class: 'fa-legal'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeLemonOutlinedIcon [

	self class: 'fa-lemon-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeLinkIcon [

	self class: 'fa-link'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeLinkedInIcon [

	self class: 'fa-linkedin'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeLinkedInSquareIcon [

	self class: 'fa-linkedin-square'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeListAlternativeIcon [

	self class: 'fa-list-alt'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeListIcon [

	self class: 'fa-list'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeListOrderedIcon [

	self class: 'fa-list-ol'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeListUnorderedIcon [

	self class: 'fa-list-ul'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeLockIcon [

	self class: 'fa-lock'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeMagicIcon [

	self class: 'fa-magic'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeMagnetIcon [

	self class: 'fa-magnet'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeMailForwardIcon [

	self class: 'fa-mail-forward'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeMapMarkerIcon [

	self class: 'fa-map-marker'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeMinusCircleIcon [

	self class: 'fa-minus-circle'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeMinusIcon [

	self class: 'fa-minus'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeMoneyIcon [

	self class: 'fa-money'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeMusicIcon [

	self class: 'fa-music'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeOutdentIcon [

	self class: 'fa-outdent'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePaperclipIcon [

	self class: 'fa-paperclip'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePauseIcon [

	self class: 'fa-pause'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePencilIcon [

	self class: 'fa-pencil'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePencilSquareOutlinedIcon [

	self class: 'fa-pencil-square-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePhoneIcon [

	self class: 'fa-phone'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePhoneSquareIcon [

	self class: 'fa-phone-square'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePictureOutlinedIcon [

	self class: 'fa-picture-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePinterestIcon [

	self class: 'fa-pinterest'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePinterestSquareIcon [

	self class: 'fa-pinterest'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePlaneIcon [

	self class: 'fa-warning'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePlayCircleOutlinedIcon [

	self class: 'fa-play-circle-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePlayIcon [

	self class: 'fa-play'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePlusCircleIcon [

	self class: 'fa-plus-circle'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePlusIcon [

	self class: 'fa-plus'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePowerOffIcon [

	self class: 'fa-power-off'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomePrintIcon [

	self class: 'fa-print'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeQRCodeIcon [

	self class: 'fa-qrcode'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeQuestionCircleIcon [

	self class: 'fa-question-circle'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeRSSIcon [

	self class: 'fa-rss'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeRandomIcon [

	self class: 'fa-random'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeRefreshIcon [

	self class: 'fa-refresh'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeRepeatIcon [

	self class: 'fa-repeat'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeRetweetIcon [

	self class: 'fa-retweet'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeRoadIcon [

	self class: 'fa-road'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeRotate180 [

	self class: 'fa-rotate-180'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeRotate270 [

	self class: 'fa-rotate-270'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeRotate90 [

	self class: 'fa-rotate-90'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeRotateLeftIcon [

	self class: 'fa-rotate-left'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeRotateRightIcon [

	self class: 'fa-rotate-right'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSaveIcon [

	self class: 'fa-save'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeScissorsIcon [

	self class: 'fa-scissors'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSearchIcon [

	self class: 'fa-search'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSearchMinusIcon [

	self class: 'fa-search-minus'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSearchPlusIcon [

	self class: 'fa-search-plus'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeShareIcon [

	self class: 'fa-share'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeShareSquareOutlinedIcon [

	self class: 'fa-share-square-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeShoppingCartIcon [

	self class: 'fa-shopping-cart'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSignInIcon [

	self class: 'fa-sign-in'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSignOutIcon [

	self class: 'fa-sign-out'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSignalIcon [

	self class: 'fa-signal'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSitemapIcon [

	self class: 'fa-sitemap'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSortAscendingIcon [

	self class: 'fa-sort-asc'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSortDescendingIcon [

	self class: 'fa-sort-desc'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSortDownIcon [

	self class: 'fa-sort-down'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSortIcon [

	self class: 'fa-sort'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSortUpIcon [

	self class: 'fa-sort-up'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeSpin [

	self class: 'fa-spin'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSquareIcon [

	self class: 'fa-square'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeSquareOutlinedIcon [

	self class: 'fa-square-o'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeStack [

	self class: 'fa-stack'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeStack1x [

	self class: 'fa-stack-1x'
]

{ #category : #'*fontawesome-core-canvas' }
WATagBrush >> fontAwesomeStack2x [

	self class: 'fa-stack-2x'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeStarHalfIcon [

	self class: 'fa-star-half'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeStarIcon [

	self class: 'fa-star'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeStarOutlinedIcon [

	self class: 'fa-star-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeStepBackwardIcon [

	self class: 'fa-step-backward'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeStepForwardIcon [

	self class: 'fa-step-forward'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeStopIcon [

	self class: 'fa-stop'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeStrikethroughIcon [

	self class: 'fa-strikethrough'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTableHeadIcon [

	self class: 'fa-th'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTableHeadLargeIcon [

	self class: 'fa-th-large'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTableHeadListIcon [

	self class: 'fa-th-list'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTableIcon [

	self class: 'fa-table'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTachometerIcon [

	self class: 'fa-tachometer'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTagIcon [

	self class: 'fa-tag'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTagsIcon [

	self class: 'fa-tags'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTasksIcon [

	self class: 'fa-tasks'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTextHeightIcon [

	self class: 'fa-text-height'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTextWidthIcon [

	self class: 'fa-text-width'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeThumbTackIcon [

	self class: 'fa-thumb-tack'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeThumbsOutlinedDownIcon [

	self class: 'fa-thumbs-o-down'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeThumbsOutlinedUpIcon [

	self class: 'fa-thumbs-o-up'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTimesCircleIcon [

	self class: 'fa-times-circle'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTimesCircleOutlinedIcon [

	self class: 'fa-times-circle-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTimesIcon [

	self class: 'fa-times'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTintIcon [

	self class: 'fa-tint'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTrashOutlinedIcon [

	self class: 'fa-trash-o'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTrophyIcon [

	self class: 'fa-trophy'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTruckIcon [

	self class: 'fa-truck'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTwitterIcon [

	self class: 'fa-twitter'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeTwitterSquareIcon [

	self class: 'fa-twitter-square'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeUnderlineIcon [

	self class: 'fa-underline'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeUndoIcon [

	self class: 'fa-undo'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeUnlockIcon [

	self class: 'fa-unlock'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeUnsortedIcon [

	self class: 'fa-unsorted'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeUploadIcon [

	self class: 'fa-upload'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeUserIcon [

	self class: 'fa-user'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeUsersIcon [

	self class: 'fa-users'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeVideoCameraIcon [

	self class: 'fa-video-camera'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeVolumeDownIcon [

	self class: 'fa-volume-down'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeVolumeOffIcon [

	self class: 'fa-volume-off'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeVolumeUpIcon [

	self class: 'fa-volume-up'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeWarningIcon [

	self class: 'fa-warning'
]

{ #category : #'*fontawesome-core-icons' }
WATagBrush >> fontAwesomeWrenchIcon [

	self class: 'fa-wrench'
]
